"""
sql_validator.py
================
Validates AI-generated SQL before execution.

Rules:
  - Only SELECT statements are allowed
  - Dangerous DML/DDL keywords are blocked
  - System table access is blocked
  - Dangerous stored-procedure prefixes are blocked
"""

import re
from dataclasses import dataclass


# ── Blocked keyword patterns ───────────────────────────────────────────────────

_BLOCKED_STATEMENTS = re.compile(
    r"^\s*(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|REPLACE|MERGE"
    r"|EXEC|EXECUTE|CALL|GRANT|REVOKE|SHUTDOWN|ATTACH|DETACH)\b",
    re.IGNORECASE | re.MULTILINE,
)

_BLOCKED_ANYWHERE = re.compile(
    r"\b(xp_|sp_|OPENROWSET|BULK\s+INSERT|LOAD_FILE|INTO\s+OUTFILE"
    r"|SHUTDOWN|GRANT|REVOKE|EXEC\b|EXECUTE\b)\b",
    re.IGNORECASE,
)

_SYSTEM_TABLES = re.compile(
    r"\b(sqlite_master|sqlite_schema|sqlite_temp_master"
    r"|sqlite_sequence|information_schema|sys\.)\b",
    re.IGNORECASE,
)

_SEMICOLON_STACKING = re.compile(r";.*\S", re.DOTALL)  # multiple statements


@dataclass
class ValidationResult:
    """Result returned by validate_sql()."""
    is_valid: bool
    error: str = ""


def validate_sql(sql: str) -> ValidationResult:
    """
    Validate that *sql* is a safe, read-only SELECT statement.

    Args:
        sql: Raw SQL string generated by the AI agent.

    Returns:
        ValidationResult with is_valid=True if safe, else is_valid=False
        with a human-readable error message.
    """
    if not sql or not sql.strip():
        return ValidationResult(False, "Empty SQL query received.")

    cleaned = sql.strip()

    # ── 1. Must start with SELECT ──────────────────────────────────────────────
    if not re.match(r"^\s*SELECT\b", cleaned, re.IGNORECASE):
        # Allow WITH … SELECT (CTE)
        if not re.match(r"^\s*WITH\b", cleaned, re.IGNORECASE):
            return ValidationResult(
                False,
                "Only SELECT queries are allowed. "
                "INSERT, UPDATE, DELETE, DROP and similar statements are blocked.",
            )

    # ── 2. Block dangerous DML / DDL at start ─────────────────────────────────
    if _BLOCKED_STATEMENTS.search(cleaned):
        return ValidationResult(
            False,
            "Query contains a blocked statement (INSERT/UPDATE/DELETE/DROP/…). "
            "Only read-only SELECT queries are permitted.",
        )

    # ── 3. Block dangerous keywords anywhere ──────────────────────────────────
    match = _BLOCKED_ANYWHERE.search(cleaned)
    if match:
        return ValidationResult(
            False,
            f"Query contains a blocked keyword: '{match.group()}'. "
            "This keyword is not permitted for security reasons.",
        )

    # ── 4. Block system table access ──────────────────────────────────────────
    match = _SYSTEM_TABLES.search(cleaned)
    if match:
        return ValidationResult(
            False,
            f"Access to system table '{match.group()}' is not allowed.",
        )

    # ── 5. Block stacked statements (SQL injection guard) ─────────────────────
    # Strip trailing semicolon first, then check for remaining content
    no_trailing = cleaned.rstrip().rstrip(";").rstrip()
    if ";" in no_trailing:
        return ValidationResult(
            False,
            "Multiple SQL statements are not allowed. Send one query at a time.",
        )

    return ValidationResult(True)
